=== Platon42/levelup-client-management/src/main/resources/static/client_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "The root schema",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "examples": [
    {
      "firstName": "John",
      "surName": "Doe6",
      "middleName": null,
      "birthDate": "2001-08-01",
      "age": 10,
      "birthPlace": null,
      "sex": "",
      "passportNum": 12348,
      "phoneNumber": "9104444040",
      "accounts": [
        {
          "accNumber": "011",
          "accCurrency": "BRL"
        },
        {
          "accNumber": "022",
          "accCurrency": "UAH"
        }
      ]
    }
  ],
  "required": [
    "firstName",
    "surName",
    "middleName",
    "birthDate",
    "age",
    "birthPlace",
    "sex",
    "passportNum",
    "phoneNumber",
    "accounts"
  ],
  "properties": {
    "firstName": {
      "$id": "#/properties/firstName",
      "type": "string",
      "title": "The firstName schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "surName": {
      "$id": "#/properties/surName",
      "type": "string",
      "title": "The surName schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "middleName": {
      "$id": "#/properties/middleName",
      "type": "null",
      "title": "The middleName schema",
      "description": "An explanation about the purpose of this instance.",
      "default": null
    },
    "birthDate": {
      "$id": "#/properties/birthDate",
      "type": "string",
      "title": "The birthDate schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "age": {
      "default": 0,
      "description": "An explanation about the purpose of this instance.",
      "examples": [
        10
      ],
      "title": "The age schema",
      "minimum": 14
    },
    "birthPlace": {
      "$id": "#/properties/birthPlace",
      "type": "null",
      "title": "The birthPlace schema",
      "description": "An explanation about the purpose of this instance.",
      "default": null
    },
    "sex": {
      "$id": "#/properties/sex",
      "type": "string",
      "title": "The sex schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""
    },
    "passportNum": {
      "$id": "#/properties/passportNum",
      "type": "string",
      "title": "The passportNum schema",
      "description": "An explanation about the purpose of this instance.",
      "minLength": 10,
      "maxLength": 10,
      "pattern": "^[0-9]*$"
    },
    "phoneNumber": {
      "default": "",
      "description": "An explanation about the purpose of this instance.",
      "title": "The phoneNumber schema",
      "pattern": "^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$"
    },
    "accounts": {
      "$id": "#/properties/accounts",
      "type": "array",
      "title": "The accounts schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          {
            "accNumber": "011",
            "accCurrency": "BRL"
          },
          {
            "accNumber": "022",
            "accCurrency": "UAH"
          }
        ]
      ],
      "items": {
        "$id": "#/properties/accounts/items",
        "anyOf": [
          {
            "$id": "#/properties/accounts/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "required": [
              "accNumber",
              "accCurrency"
            ],
            "properties": {
              "accNumber": {
                "$id": "#/properties/accounts/items/anyOf/0/properties/accNumber",
                "type": "string",
                "title": "The accNumber schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""
              },
              "accCurrency": {
                "$id": "#/properties/accounts/items/anyOf/0/properties/accCurrency",
                "type": "string",
                "title": "The accCurrency schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": [
                  "BRL"
                ]
              }
            },
            "additionalProperties": true
          }
        ]
      }
    }
  },
  "additionalProperties": true
}

=== Platon42/levelup-client-management/src/main/resources/templates/createClient.json
{
  "firstName": "Ivan",
  "surName": "Venus",
  "middleName": "W",
  "birthDate": "2001-08-01",
  "age": 20,
  "birthPlace": "Russia",
  "sex": "male",
  "passportNum": "1410445442",
  "phoneNumber": "+78411001101",
  "accounts": [{
    "accNumber": "0511",
    "accCurrency": "USD"
  },
    {
      "accNumber": "02222",
      "accCurrency": "USD"
    }
  ]
}
